level-manage-permission: money.edit
bossbar: falseo
chatmsg: "%prefix%%1$s §7» §f%2$s"
enablechat: true
# %1$s correspond au pseudo du joueur
# %2$s corresponde au message
# %rank% correspond au préfix du rank
money-manage-permission: money.edit
sql:
  host: localhost
  port: 3306
  database: endoskull
  user: endoskull
  password: 2M3hz44XRkkZkph3ExYqm2use5gJQG