name: EndoSkull-API
version: 1.0
description: Api of EndoSkull (level, money, keys, rank, moderation)
website: https://endoskull.fr
author: BebeDlaStreat
main: fr.endoskull.api.Main
softdepend:
  - DeluxeHub_EndoSkull
  - HologramAPI
  - ActionBarAPI
commands:
  level:
    aliases: [xp]
  permission:
    aliases: [perm, perms, permissions]
    permission: rank.permission.edit
  endoskullapi:
    description: reload la config
  boxset:
    permission: box.set
  key:
    permission: key.edit
  coins:
    aliases: [money, bal, balance, solde]
  booster:
    aliases: [boost]
  boutique:
    description: ouvrir la boutique
  discord:
    aliases: [vote]
  lobby:
    aliases: [pvpkit, bedwars]
  tag:
    permission: endoskull.tag
  load: