name: EndoSkull-API
version: 1.0
description: Api of EndoSkull (level, money, keys, rank, moderation)
website: https://endoskull.fr
author: BebeDlaStreat
main: fr.endoskull.api.Main
softdepend:
  - HologramAPI
commands:
  level:
    aliases: [xp]
  permission:
    aliases: [perm, perms, permissions]
    permission: rank.permission.edit
  endoskullapi:
    description: reload la config
  boxset:
    permission: box.set
  key:
    permission: key.edit
  coins:
    aliases: [money, bal, balance, solde]
  booster:
    aliases: [boost]
  boutique:
    description: ouvrir la boutique
  discord:
    aliases: [vote]
  lobby:
    aliases: [pvpkit, bedwars]
  load:
  motdeditor:
    permission: endoskull.motd
  join:
#  profile:
#    aliases: [profil, stat, stats]
  deploy:
    permission: endoskull.deploy
  sound:
    permission: endoskull.admin.sound
  endoskull:
    permission: endoskull.admin
    aliases: [es, endo]
  forward:
    description: 'Forward a command to the bungee proxy'
    usage: /<command> <player-name or 'console'> <bungee_command> [arg]
    permission: ${project.artifactId}.command.forward
