name: EndoSkullCore
version: 1.0
description: Core of EndoSkull
website: https://endoskull.fr
author: BebeDlaStreat
main: fr.endoskull.api.Main
softdepend:
  - ProtocolLib
  - Vulcan
  - ReplaySystem
commands:
  level:
    aliases: [xp]
  permission:
    aliases: [perm, perms, permissions]
    permission: rank.permission.edit
  endoskullapi:
    description: reload la config
  boxset:
    permission: box.set
  key:
    permission: key.edit
  coins:
    aliases: [money, bal, balance, solde]
  booster:
    aliases: [boost]
  boutique:
    description: ouvrir la boutique
    aliases:
      - shop
      - store
  discord:
    aliases: [vote]
  lobby:
    aliases: [pvpkit, bedwars]
  load:
  motdeditor:
    permission: endoskull.motd
  join:
#  profile:
#    aliases: [profil, stat, stats]
  deploy:
    permission: endoskull.deploy
  sound:
    permission: endoskull.admin.sound
  endoskull:
    permission: endoskull.command.endoskull
    aliases: [es, endo]
  forward:
    description: 'Forward a command to the bungee proxy'
    usage: /<command> <player-name or 'console'> <bungee_command> [arg]
    permission: ${project.artifactId}.command.forward
  staff:
    permission: endoskull.command.staff
  about:
  sanction:
    permission: endoskull.command.sanction
  report:
    permission: endoskull.report
permissions:
  endoskull.report:
    default: true